### ISSUE TITLE
Extra data

### ISSUE THREAD

**Issue by WillSwales** [owen-kellie-smith/chart2#2]
Add data to each chart

Gig history
Solos (improv/written)
Style
Dance speed
Length

**Comment by owen-kellie-smith** [comment]
Solos could be implemented by having a solos table that just lists triples:
(arrangementID, partID, soloStyleID)

where soloStyleID is constrained to be an id from a solostyle table, and solostyle table has just 2 fields:
soloStyleID (auto-increment), styleDescription (text)
e.g.
1, Written
2, Improvised

**Comment by owen-kellie-smith** [comment]
Simililarly (as an arrangement might fit more than one style). styles could be pairs
(musicStyleID, arrangmentID)

**Comment by owen-kellie-smith** [comment]
Speed and length can be numerical properties of the arrangment

**Comment by owen-kellie-smith** [comment]
Speed isn't a property of the chart but of the pair (chart, gig) e.g. Pennsylvania 6-5000 168 for Bev, 130 for VE Days

**Comment by owen-kellie-smith** [comment]
GIg history shown for each arangement in acf9e5117e15ba2e2d2ab94c286618a867a42945.  All the rest can go in notes (i.e. unstructured)
