### ISSUE TITLE
Make filler pages for printing optional

### ISSUE THREAD

**Issue by WillSwales** [owen-kellie-smith/chart2#34]
when downloading a gig pad, over half the pages are "blank on purpose". this fulfils one use case (makes it easy for someone to print the whole pad double-sided) but fails others:
- someone who just wants to view the pad digitally (has to scroll through many redundant pages)
- someone who just wants to view the pad digitally and then print off one or two charts (no need for filler pages)

Solutions:
- Make the filler pages optional (ideal).
- Add page numbers to the contents page so people using splitpdf (or similar) can see which pages they need to extract

**Comment by owen-kellie-smith** [comment]
Goo idea.

**Comment by owen-kellie-smith** [comment]
Good

**Comment by owen-kellie-smith** [comment]
Filler Made optional in b5d11d38e136dc09dde099787c18b1f05a56b227  (edit to Gig.php)
