### ISSUE TITLE
Add filter: vocals (solo)

### ISSUE THREAD

**Issue by WillSwales** [owen-kellie-smith/chart2#55]

**Comment by owen-kellie-smith** [comment]
For starters, fix http://tsbchart.com/test/?action=getGig&gigID=135&part=Vocal+Solo which should list all categorised charts (in a set list or a practice list or a dance category) what have a vocal solo ... but actually outputs a nearly blank page

**Comment by owen-kellie-smith** [comment]
Fixed.  See e.g. http://tsbchart.com/?action=getGig&gigID=135&part=Vocal+Solo&includeMusic=exclude
