### ISSUE TITLE
Add functionality to download all parts for one selected pad

### ISSUE THREAD

**Issue by WillSwales** [owen-kellie-smith/chart2#57]
with or without padding

**Comment by owen-kellie-smith** [comment]
Try http://tsbchart.com/maintenance/?action=getPartsForSet&gigID=132

**Comment by owen-kellie-smith** [comment]
(Doesn't have any option on padding.  Get link via e.g. tsbchart.com > maintenance > Edit set > Nder "Output parts for set" select "Practice on the Sunny Side ..." [Get parts (output...)]

**Comment by owen-kellie-smith** [comment]
Also try (for single chart) http://tsbchart.com/?action=getChart&allParts&arrangement[]=366

**Comment by owen-kellie-smith** [comment]
single chart allParts comes with obligatory padding

**Comment by owen-kellie-smith** [comment]
Without padding: http://tsbchart.com/?action=getChart&arrangement[]=%20366&allParts&noPad

**Comment by WillSwales** [comment]
*Thumbs up*

I hope you weren't up all night doing that!

**Comment by owen-kellie-smith** [comment]
Hooray!  Hee hee :)
